extends: ['@commitlint/config-conventional']

rules:
  scope-enum:
    - 2
    - always
    - [commitlint, confluence-sync, infracost, lint-workflows, semantic-release, sonar-scanner, tfe-remote-plan, tlz-checks]
