extends: ['@commitlint/config-conventional']

rules:
  scope-enum:
    - 2
    - always
    - [commitlint, confluence-sync, gitops, infracost, lint-workflows, semantic-release, sonar-scanner, tfe-remote-run, tlz-checks, tlz-prepare-workspace, tlz-speculative-plan]
