name: semantic-pr-title

on:
  workflow_call:
    inputs:
      requireScope:
        type: boolean
        required: false
        default: false
      scopes:
        type: string
        required: false
      types:
        type: string
        required: false

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.6
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          requireScope: ${{ inputs.requireScope }}
          scopes: ${{ inputs.scopes }}
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          types: ${{ inputs.types }}
          validateSingleCommit: true
