name: commitlint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_call:
    inputs:
      configFile:
        description: Commitlint config file path
        type: string
        required: false
        default: .commitlintrc.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commitlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: ${{ inputs.configFile }}
          failOnWarnings: true
