name: commitlint

on:
  pull_request:
    types:
      - opened
      - edited
  workflow_call:
    inputs:
      configFile:
        description: Commitlint config file path
        type: string
        required: false
        default: .commitlintrc.yaml

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v4
        with:
          configFile: ${{ inputs.configFile }}
          failOnWarnings: true
