name: infracost

on:
  workflow_call:
    inputs:
      tf_workspace:
        type: string
        required: true
        description: Terraform Workspace
    secrets:
      api_key:
        required: true
        description: Infracost API Key
      tfe_token:
        required: true
        description: Terraform Enterprise API Token

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache
  TF_WORKSPACE: ${{ inputs.tf_workspace }}

jobs:
  infracost:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cache terraform plugins
        uses: actions/cache@v2
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: install terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.tfe_token }}
          terraform_wrapper: false

      - name: terraform init
        run: terraform init

      - name: terraform plan
        uses: ./.github/actions/tfe-remote-plan
        with:
          output: plan.json
          tfe_token: ${{ secrets.tfe_token }}

      - name: setup infracost
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.api_key }}

      - name: generate infracost json
        run: infracost breakdown --path plan.json --format json --out-file /tmp/infracost.json

      - name: post infracost comment
        uses: infracost/actions/comment@v1
        with:
          path: /tmp/infracost.json
          behavior: update
