name: infracost

on:
  workflow_call:
    inputs:
      artifact_plan_name:
        type: string
        required: true # todo: make this optional, run plan if not set
        description: Artifact name containing the planfile
    secrets:
      api_key:
        required: true
        description: Infracost API Key

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache

jobs:
  infracost:
    runs-on: ubuntu-latest
    concurrency: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: prepare workspace
        uses: clickdealer/github-actions/.github/actions/tlz-prepare-workspace@v1
        with:
          artifact_plan_name: ${{ inputs.artifact_plan_name }}

      - name: setup infracost
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.api_key }}

      - name: generate infracost json
        run: infracost breakdown --path plan.json --format json --out-file /tmp/infracost.json

      - name: post infracost comment
        uses: infracost/actions/comment@v1
        with:
          path: /tmp/infracost.json
          behavior: update
