name: lint-workflows

on:
  pull_request:
    paths:
      - '.github/workflows/*.yaml'
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-actionlint@v1
