name: lint-workflows

on:
  pull_request:
    paths:
      - '.github/workflows/*.yaml'
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-workflows:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: -ignore property "github_token" is not defined in object type
          fail_on_error: true
