name: lint-workflows

on:
  pull_request_target:
    paths:
      - '.github/workflows/*.yaml'
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: reviewdog/action-actionlint@v1
        with:
          fail_on_error: true
