name: lint-workflows

on:
  pull_request:
    paths:
      - '.github/workflows/*.yaml'
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: -ignore property "github_token" is not defined in object type
          fail_on_error: true
