name: php-workflow

on:
  workflow_call:
    inputs:
      runs-on:
        description: The type of machine to run the job on
        type: string
        required: false
        default: ubuntu-latest
      skip-cs-fixer:
        description: Force CS Fixer to skip
        type: boolean
        required: false
        default: false
      skip-phpstan:
        description: Force PHPStan to skip
        type: boolean
        required: false
        default: false
      skip-phpunit:
        description: Force PHPUnit to skip
        type: boolean
        required: false
        default: false

    secrets:
      COMPOSER_AUTH:
        description: PHP auth
        required: true

jobs:
  php-workflow:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install Composer Dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      - name: PHP CS Fixer config file exists
        uses: andstor/file-existence-action@v1
        id: cs_fixer_config_file
        with:
          files: php-cs-fixer.dist.php

      - name: Run PHP CS Fixer
        if: inputs.skip-cs-fixer == false && steps.cs_fixer_config_file.outputs.files_exists == 'true'
        run: ./vendor/bin/php-cs-fixer fix --dry-run --config=php-cs-fixer.dist.php --allow-risky=yes --stop-on-violation

      - name: PHPStan config file exists
        uses: andstor/file-existence-action@v1
        id: phpstan_config_file
        with:
          files: phpstan.neon

      - name: Run PHPStan
        if: inputs.skip-phpstan == false && steps.phpstan_config_file.outputs.files_exists == 'true'
        run: ./vendor/bin/phpstan analyse

      - name: PHPUnit config file exists
        uses: andstor/file-existence-action@v1
        id: phpunit_config_file
        with:
          files: phpunit.xml

      - name: Run PHPUnit
        if: inputs.skip-phpunit == false && steps.phpunit_config_file.outputs.files_exists == 'true'
        run: ./vendor/phpunit/phpunit/phpunit

