name: tlz-speculative-plan

on:
  workflow_call:
    secrets:
      tfe_token:
        description: Terraform Enterprise Token
        required: true
    outputs:
      artifact_name:
        description: Artifact name containing the planfile
        value: tfplan

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache

jobs:
  tlz-speculative-plan:
    runs-on: ubuntu-latest
    steps:
      - name: export branch variables
        id: export
        run: |
          if [[ $GITHUB_BASE_REF = master ]]; then
            TF_WORKSPACE=prod-infra
          elif [[ $GITHUB_BASE_REF = staging ]]; then
            TF_WORKSPACE=stage-infra
          elif [[ $GITHUB_BASE_REF = develop ]]; then
            TF_WORKSPACE=dev-infra
          fi

          echo "::set-output name=tf_workspace::${TF_WORKSPACE}"

      - name: prepare workspace
        uses: clickdealer/github-actions/.github/actions/tlz-prepare-workspace@edge
        with:
          terraform_init_backend: 'true'
          tfe_token: ${{ secrets.tfe_token }}
          tfe_workspace: ${{ steps.export.outputs.tf_workspace }}

      - name: tfe remote run
        uses: clickdealer/github-actions/.github/actions/tfe-remote-run@edge
        with:
          output: plan.json
          tfe_token: ${{ secrets.tfe_token }}

      - name: upload plan artifact
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: plan.json
          if-no-files-found: error
          retention-days: 1
