name: tlz-speculative-plan

on:
  workflow_call:
    inputs:
      compute_tf_workspace:
        description: Whether to compute the tf_workspace from the branch
        required: false
        type: boolean
        default: true
      tf_workspace:
        description: Terraform Workspace (If not passed in will be computed from branch)
        required: false
        type: string
    secrets:
      tfe_token:
        description: Terraform Enterprise Token
        required: true
    outputs:
      artifact_name:
        description: Artifact name containing the planfile
        value: tfplan

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  export:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    outputs:
      tf_workspace: ${{ steps.export.outputs.tf_workspace }}
    steps:
      - name: export branch variables
        if: inputs.compute_tf_workspace
        id: export
        run: |
          if [[ $GITHUB_BASE_REF = master ]]; then
            TF_WORKSPACE=prod-infra
          elif [[ $GITHUB_BASE_REF = staging ]]; then
            TF_WORKSPACE=stage-infra
          elif [[ $GITHUB_BASE_REF = develop ]]; then
            TF_WORKSPACE=dev-infra
          fi

          echo "::set-output name=tf_workspace::${TF_WORKSPACE}"

  tlz-speculative-plan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: export
    env:
      TF_WORKSPACE: ${{ inputs.tf_workspace || needs.export.outputs.tf_workspace }}
    steps:
      - name: prepare workspace
        uses: clickdealer/github-actions/.github/actions/tlz-prepare-workspace@v1
        with:
          terraform_init_backend: 'true'
          tfe_token: ${{ secrets.tfe_token }}

      - name: tfe remote run
        uses: clickdealer/github-actions/.github/actions/tfe-remote-run@v1
        with:
          output: plan.json
          tfe_token: ${{ secrets.tfe_token }}

      - name: upload plan artifact
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: plan.json
          if-no-files-found: error
          retention-days: 1
