name: Terraform Enterprise Remote Plan
description: Run a remote plan and generate a plan file
inputs:
  output:
    required: true
    description: File path to generate Terraform plan
  tfe_host:
    required: false
    default: app.terraform.io
    description: Terraform Enterprise Hostname
  tfe_token:
    required: true
    description: Terraform Enterprise Token
runs:
  using: composite
  steps:
    - shell: bash
      run: ${{ github.action_path }}/tfe-remote-plan.sh
